# Russian dossel

Given a[i] and b[i], find largest set (i) such that

```
a[i]<=a[j] b[i]<=b[j] if i<j
```

```
1<=a,b.lengths<=5000
1<=a[i],b[i]<=10**4
```

## Simple idea

In [96]:
class Solution:
    def maxEnvelopes(self,envelopes):
        es = sorted(envelopes)
        print(es)
        n = len(es)
        dp = [0]*(n+1)
        j = 0
        ans = 0
        stack1 = [float('-inf')]
        stack3 = [0]
        stack2 = [float('inf')]
        stack4 = [0]
        stack5 = [[]]
        for i in range(n):
            while es[j][0]<es[i][0]:
                while stack1[-1]>es[j][1]:
                    stack1.pop()
                    stack3.pop()
                stack1.append(es[j][1])
                stack3.append(j)
                coll = []
                while stack2[-1]<es[j][1]:
                    stack2.pop()
                    stack4.pop()
                    coll = stack5.pop()+coll
                stack2.append(es[j][1])
                stack4.append(j)
                coll.append(stack2[-1])
                stack5.append(coll)
                j += 1
            # [0:j] are all ev with w less than i
            dp[i] = 1
            
            print(es[i][1],f'{str(stack1):40s}',f'{str(stack2):50s}',f'{str([es[k][1] for k in range(j) if es[k][1]<es[i][1]]):60s}', f'{str(stack5[-1]):40s}',max([-999]+[dp[k] for k in stack3]),max([dp[k] for k in stack4]),list(zip(*es))[1][:j],)
            print(stack5)
            for k in range(j):
                if es[k][1]<es[i][1]:
                    dp[i] = max(dp[i],dp[k]+1)
            ans = max(ans,dp[i])
        return ans

In [116]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [float('-inf')]*(n+1)
        
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&(-u)
            
    def q(self,u):
        ans = float('-inf')
        while u>0:
            ans = max(self.data[u],ans)
            u -= u&(-u)
        return ans
    
arr = np.random.randint(1,100,(20,2))
BIT = Fenwick(max([x[0] for x in arr]))
for i,(x,y) in enumerate(arr):
    BIT.update(x,y)
    print(f'{str(BIT.q(x-1)):5s}',f'{str([p[1] for p in arr[:i+1]]):80s}',f'{str([p[1] for p in arr[:i] if p[0]<x]):80s}',max([-999]+[p[1] for p in arr[:i] if p[0]<x]))
    
    

-inf  [52]                                                                             []                                                                               -999
52    [52, 50]                                                                         [52]                                                                             52
-inf  [52, 50, 87]                                                                     []                                                                               -999
-inf  [52, 50, 87, 87]                                                                 []                                                                               -999
87    [52, 50, 87, 87, 73]                                                             [52, 87, 87]                                                                     87
87    [52, 50, 87, 87, 73, 15]                                                         [52, 50, 87, 87, 73]                                

In [132]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [0]*(n+1)
        
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&(-u)
    
    def q(self,u):
        ans = 0
        while u>0:
            ans = max(self.data[u],ans)
            u -= u&(-u)
        return ans
            
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        n = len(es)
        dp = [0]*n
        j = 0
        digi = {x:i+1 for i,x in enumerate(sorted(set([x[1] for x in es])))}
        print(digi)
        BIT = Fenwick(len(digi))
        for i,(w,h) in enumerate(es):
            while es[j][0]<es[i][0]:
                BIT.update(digi[es[j][1]],dp[j])
                j += 1
            dp[i] = max(1,BIT.q(digi[es[i][1]]-1)+1)
        return max(dp)

In [134]:
class Fenwick:
    def __init__(self,arr):
        self.n = n
        self.digi = {x:i+1 for i,x in sorted(set(arr))}
        self.data = [0]*(n+1)
        
    def update(self,u,m):
        u = self.digi[u]
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&(-u)
            
    def q(self,u):
        u = self.digi[u]
        ans = 0
        while u>0:
            ans = max(ans,self.data[u])
            u -= u&(-u)
        return ans
        
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        BIT = Fenwick([x[1] for x in es])
        j = 0
        dp = [0]*n
        for i,(w,h) in enumerate(es):
            while es[j][0]<es[i][0]:
                BIT.update(es[j][1],dp[j])
                j += 1
            dp[i] = max(1,BIT.q(es[i][1]-1)+1)
        return max(dp)

In [143]:
class Fenwick:
    def __init__(self,arr):
        self.digi = {x:i+1 for i,x in enumerate(sorted(set(arr)))}
        self.n = len(self.digi)
        self.data = [0]*(self.n+1)
        
    def update(self,u,m):
        u = self.digi[u]
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&-u
    
    def q(self,u):
        u = self.digi[u]-1
        ans = 0
        while u>0:
            ans = max(ans,self.data[u])
            u -= u&-u
        return ans
    
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        n = len(es)
        dp = [0]*n
        BIT = Fenwick([x[1] for x in es])
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                BIT.update(es[j][1],dp[j])
                j+=1
            dp[i] = max(1,BIT.q(h)+1)
        return max(dp)

In [145]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [0]*(n+1)
        
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&-u
    
    def q(self,u):
        ans = 0
        while u>0:
            ans = max(self.data[u],ans)
            u -= u&-u
        return ans
    
def Solution:
    def maxEnvelopes(self,es):
        digi = {x:i+1 for i in enumerate(sorted(set([x[1] for x in es])))}
        BIT = Fenwick(len(digi))
        n = len(es)
        dp = [0]*n
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                BIT.update(es[j][1],dp[j])
                j += 1
            dp[i] = max(1,BIT.q(digi[h]-1)+1)
        return max(dp)

SyntaxError: invalid syntax (<ipython-input-145-8d4150479cba>, line 18)

In [151]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [0]*(n+1)
        
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&-u
            
    def q(self,u):
        ans = 0
        while u>0:
            ans = max(self.data[u],ans)
            u -= u&-u
        return ans
    
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        digi = {x:i+1 for i,x in enumerate(sorted(set([x[1] for x in es])))}
        BIT = Fenwick(len(digi))
        dp = [0]*len(es)
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                BIT.update(es[j][1],dp[j])
                j += 1
            dp[i] = max(1,BIT.q(digi[h]-1)+1)
        return max(dp)

In [153]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [0]*n
        
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&-u
            
    def q(self,u):
        ans = 0
        while u>0:
            ans = max(self.data[u],ans)
            u -= u&-u
        return ans
    
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        digi = {x:i+1 for i,x in enumerate(sorted(set([x[1] for x in es])))}
        BIT = Fenwick(len(digi))
        dp = [0]*len(es)
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                BIT.update(digi[es[j][1]],dp[j])
                j += 1
            dp[i] = max(1,BIT.q(digi[h]-1)+1)
        return max(dp)

In [156]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [0]*(n+1)
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&-u
    def q(self,q):
        ans = 0
        while u>0:
            ans = max(self.data[u],ans)
            u -= u&-u
        return ans
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        digi = {x:i+1 for i,x in enumerate(sorted(set([x[1] for x in es])))}
        BIT = Fenwick(len(digi))
        dp = [0]*len(es)
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                BIT.update(digi[es[j][1]],dp[j])
                j += 1
            dp[i] = max(1,1+BIT.q(digi[h]-1))
        return max(dp)

In [158]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [0]*(n+1)
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&-u
    def q(self,u):
        ans = 0
        while u>0:
            ans = max(ans,self.data[u])
            u -= u&-u
        return ans
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        digi = {x:i+1 for i,x in enumerate(sorted(set([x[1] for x in es])))}
        BIT = Fenwick(len(digi))
        dp = [0]*len(es)
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                BIT.update(digi[es[j]],dp[j])
                j += 1
            dp[i] = max(1,BIT.q(digi[h]-1)+1)
        return max(dp)

In [231]:
class Fenwick:
    def __init__(self,n):
        self.n = n
        self.data = [0]*(n+1)
    def update(self,u,m):
        while u<=self.n:
            self.data[u] = max(self.data[u],m)
            u += u&-u
    def q(self,u):
        ans = 0
        while u>0:
            ans = max(ans,self.data[u])
            u -= u&-u
        return ans
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        digi = {x:i+1 for i,x in enumerate(sorted(set([x[1] for x in es])))}
        BIT = Fenwick(len(digi))
        dp = [0]*len(es)
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                BIT.update(digi[es[j][1]],dp[j])
                j += 1
            dp[i] = max(1,BIT.q(digi[h]-1)+1)
        return max(dp)

## Binary

In [203]:
from bisect import *

for _ in range(10):
    a = np.random.randint(1,100,10)
    b = sorted(np.random.randint(1,100,10))
    stack = []
    stack2 = []
    for j,i in enumerate(a):
        if not stack or i>stack[-1]:
            stack.append(i)
            stack2.append([b[j]])
        else:
            L,R = 0,len(stack)-1
            while L<R:
                mid = L+(R-L>>1)
                if i<=stack[mid]:
                    R = mid
                else:
                    L = mid+1
            # print(L,bisect_left(stack,i,key = lambda x:x[-1]))
            stack[L] = i
            stack2[L].append(b[j])
        print(a,b,f'{str(stack):40s}',stack2)
a = [1,3,5,2,7,9]
a[bisect_left(a,3):]

[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [65]                                     [[2]]
[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [41]                                     [[2, 3]]
[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [41, 82]                                 [[2, 3], [6]]
[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [41, 67]                                 [[2, 3], [6, 8]]
[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [41, 67, 77]                             [[2, 3], [6, 8], [26]]
[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [41, 67, 73]                             [[2, 3], [6, 8], [26, 32]]
[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [41, 67, 73, 93]                         [[2, 3], [6, 8], [26, 32], [48]]
[65 41 82 67 77 73 93 60 63 12] [2, 3, 6, 8, 26, 32, 48, 74, 82, 95] [41, 60, 73, 93]                

[7, 9]

In [223]:
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        stack = []
        j = 0
        ans = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                if not stack or es[j][1]>=stack[-1]:
                    stack.append(es[j][1])
                else:
                    # stack[pos-1]<h, stack[pos]>=h
                    stack[bisect_left(stack,es[j][1])] = es[j][1]
                j += 1
            ans = max(ans,bisect_left(stack,h)+1)
        return ans
            

In [274]:
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        # print(es)
        j = 0
        dp = [None]*len(es)
        stack = [0]
        # ws = list(zip(*es))[0]
        # hs = list(zip(*es))[1]
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                # print(j,dp[j],len(stack))
                if dp[j]==len(stack):
                    stack.append(es[j][1])
                else:
                    stack[dp[j]] = min(stack[dp[j]],es[j][1])
                j += 1
            dp[i] = bisect_left(stack,h)
            # print(stack,h,dp,dp[i])
        return max(dp)

In [279]:
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        dp = [0]*len(es)
        minh = [0]
        j = 0
        for w,h in es:
            while es[j][0]<w:
                if dp[j]==len(minh):
                    minh.append(dp[j])
                else:
                    minh[dp[j]] = min(minh[dp[j]],es[j][1])
                j += 1
            dp[i] = bisect_left(dp,h)
        return max(dp)

In [281]:
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        dp = [0]*len(es)
        j = 0
        minh = [0]
        for w,h in es:
            while es[j][0]<w:
                if dp[j]==len(minh):
                    minh.append(es[j][1])
                else:
                    minh[dp[j]] = min(minh[dp[j]],es[j][1])
            dp[i] = bisect_left(minh,h)
        return max(dp)

In [285]:
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        dp = [0]*len(es)
        minh = [0]
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                if dp[j]==len(minh):
                    minh.append(es[j][1])
                else:
                    mihh[dp[j]] = min(minh[dp[j]],es[j][1])
            dp[i] = bisect_left(minh,h)
        return max(dp)

In [287]:
class Solution:
    def maxEnvelopes(self,es):
        es = sorted(es)
        dp = [0]*len(es)
        minh = [0]
        j = 0
        for i,(w,h) in enumerate(es):
            while es[j][0]<w:
                if dp[j]==len(minh):
                    minh.append(es[j][1])
                else:
                    minh[dp[j]] = min(minh[dp[j]],es[j][1])
                j += 1
            dp[i] = bisect_left(minh,h)
        return max(dp)

In [288]:
import numpy as np
inp = [
    # [np.random.randint(1,10,(20,2)).tolist(),5],
    [[[5,4],[6,4],[6,7],[2,3]],3],
    [[[1,1],[1,1],[1,1],[1,1]],1],
    [[[30,50],[12,2],[3,4],[12,15]],3],
    [[[1,2]],1],
    [[[5,4],[6,4],[6,7],[2,3]],3],
    [[[4,5],[4,6],[6,7],[2,3],[1,1]],4],
    [[[i,i] for i in range(1,5001)],5000]
]
for e,o in inp:
    t = Solution().maxEnvelopes(e)
    if t!=o:
        print(e,o,t)


In [206]:
bisect_left([1,2,2,2,3],2)

1